version: '3'
services:

  kafka:
    image: docker.redpanda.com/vectorized/redpanda:v22.2.7
    container_name: kafka
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://kafka:28082,OUTSIDE://localhost:8082
    networks:
      - bridge_net

  # On lower-end hardware comment the consumer to save precious hw resources
  # consumer:
  #   image: kafkacat_consumer
  #   container_name: consumer
  #   tty: true
  #   environment:
  #     - TOPIC=test
  #   networks:
  #     - bridge_net
  #   depends_on:
  #     - kafka

  server:
    image: tokioserver:latest
    container_name: server
    environment:
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=8888
      - STATS_INTERVAL=10
      - RUST_LOG=INFO
      - BUFFER_SIZE=1450
      - CACHE_SIZE=10000
      - WORKER_THREADS=4 #worker threads for the server 0 --> #CPU core
      - KAFKA_BROKERS=kafka:29092
      - KAFKA_TOPIC=test
      - KAFKA_PARTITION_STRATEGY=STICKY_ROUND_ROBIN
      - KAFKA_REQUEST_REQUIRED_ACKS=1
      - KAFKA_COMPRESSION_CODEC=zstd
      - KAFKA_BATCH_NUM_MESSAGES=10000 
      - KAFKA_RETRIES=1
      - KAFKA_QUEUE_BUFFERING_MAX_MS=100 #ALIAS LINGER.MS
      - KAFKA_QUEUE_BUFFERING_MAX_MESSAGES=10000000 #big chunky batches + more aggresive compression
      - KAFKA_QUEUE_BUFFERING_MAX_KBYTES=1048576
    networks:
      - bridge_net
    depends_on:
      - kafka

  client:
    image: udpclient:latest
    container_name: client
    environment:
    - DEST_ADDR=server:8888
    - CONNECTIONS=20
    - PAYLOAD_SIZE=1450
    - RATE=18150 #3620000 4.2Gb mark 
    - WORKERS=4 #worker threads for the client 0 --> #CPU core
    networks:
      - bridge_net
    depends_on:
      - server

networks:
  bridge_net:
    name: bridge_net
    driver: bridge