version: '3'
services:

  kafka:
    image: docker.redpanda.com/vectorized/redpanda:v22.3.13
    container_name: kafka
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://kafka:28082,OUTSIDE://localhost:8082
    networks:
      - bridge_net

  # On lower-end hardware comment the consumer to save precious hw resources
  # consumer:
  #   image: kafkacat_consumer
  #   container_name: consumer
  #   tty: true
  #   environment:
  #     - TOPIC=test
  #     - PROTO=true #should follow forwarder.environment.USE_PROTO
  #   networks:
  #     - bridge_net
  #   depends_on:
  #     - kafka

  forwarder:
    image: udpforwarder:latest
    container_name: forwarder
    environment:
      - LISTEN_IP=0.0.0.0
      - LISTEN_PORT=8888
      - USE_DTLS=false
      - SERVER_KEY=/server-key.pem
      - SERVER_CERT=/server-cert.pem
      - STATS_INTERVAL=10
      - RUST_LOG=INFO
      - BUFFER_SIZE=1450
      - CACHE_SIZE=2000
      - WORKER_THREADS=3 #worker threads 0 --> #CPU core
      - USE_PROTO=false
      - KAFKA_BROKERS=kafka:29092
      - KAFKA_TOPIC=test
      - KAFKA_PARTITION_STRATEGY=STICKY_ROUND_ROBIN
      - KAFKA_REQUEST_REQUIRED_ACKS=1
      - KAFKA_COMPRESSION_CODEC=zstd
      - KAFKA_BATCH_NUM_MESSAGES=10000
      - KAFKA_RETRIES=1
      - KAFKA_QUEUE_BUFFERING_MAX_MS=10 #ALIAS LINGER.MS
      - KAFKA_QUEUE_BUFFERING_MAX_MESSAGES=10000000 #big chunky batches -> more compression
      - KAFKA_QUEUE_BUFFERING_MAX_KBYTES=1048576
    networks:
      - bridge_net
    depends_on:
      - kafka

  client:
    image: udpclient:latest
    container_name: client
    environment:
    - DEST_ADDR=forwarder:8888
    - CONNECTIONS=20
    - PAYLOAD_SIZE=1450
    - USE_DTLS=false
    - CA_FILE=/ca-cert.pem
    - RATE=20240 #19380 4.5Gb/s limit
    - WORKERS=3 #worker threads for the client 0 --> #CPU core
    - SLEEP_TASK_SPAWN=200 #ms to wait between connections creation
   
    #10k scenario 4.2Gb/s
    #10000 1450 36 3 2
    networks:
      - bridge_net
    depends_on:
      - forwarder

networks:
  bridge_net:
    name: bridge_net
    driver: bridge